version: "3"
services:
  app:
    build: .
    command: jekyll serve --host=0.0.0.0 --force_polling --incremental
    volumes:
      - .:/app:delegated
    ports:
      - "4000:4000"

  fast-publish:
    build: .
    command: bash
    volumes:
      - .:/app:delegated
      - ~/.ssh:/home/deploy/.ssh
